-- tables
DROP TABLE Takes;
DROP TABLE Enrolls_in;
DROP TABLE Subject;
/* DROP TABLE AssociateLecturer;
DROP TABLE SeniorLecturer;
DROP TABLE Lecturer;
DROP TABLE Tutor;
DROP TABLE Technician;
DROP TABLE AdminTbl; */
DROP TABLE Student;
DROP TABLE Staff;
DROP TABLE DegreeTbl;
DROP TABLE Lab;
DROP TABLE Classroom;
DROP TABLE Office;
-- DROP TABLE Person;
DROP TABLE Building;
DROP TABLE Faculty;
DROP TABLE Professor;
DROP TABLE Campus;

-- types
DROP TYPE SubjectT;
DROP TYPE AssociateLecturerT;
DROP TYPE SeniorLecturerT;
DROP TYPE LecturerT;
DROP TYPE TutorT;
DROP TYPE TechnicianT;
DROP TYPE AdminT;
DROP TYPE StudentT;
DROP TYPE StaffT;
DROP TYPE TechnicianskillsT;
DROP TYPE OfficeskillsT;
DROP TYPE ComputerskillsT;
DROP TYPE DegreeT;
DROP TYPE LabT;
DROP TYPE LabEquipmentT;
DROP TYPE ClassroomT;
DROP TYPE OfficeT;
DROP TYPE PersonT;
DROP TYPE BuildingT;
DROP TYPE FacultyT;
DROP TYPE ResearchCentreListT;
DROP TYPE ResearchCentreT;
DROP TYPE RCUnitT;
DROP TYPE SchoolListT;
DROP TYPE SchoolT;
DROP TYPE DepartmentListT;
DROP TYPE DepartmentT;
DROP TYPE ProfessorListT;
DROP TYPE ProfessorT;
DROP TYPE CampusT;